name: PlayerPeak
version: 1.7.9
main: RedJaVa.com.crimsonempires.PlayerPeakCore
softdepend: [Vault]
commands:
  peak:
    description: Shows the peak count and can be used as a help tool for the PlayerPeak Plugin
    permission: peak.command
permission:
  peak.get:
    description: Permission for the cash destribution section of the plugin
    default: op
  peak.command:
    description: Gives access to the PlayerPeak commands.
    default: op
  peak.command.admin:
    description: Gives access to the reload command.
    default: op